### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by HongSenDu** [erl-ang/GoT-w4111#1]
hi

**Comment by erl-ang** [comment]
wut

**Comment by jesspli2192** [comment]
hong sen du.

**Comment by jesspli2192** [comment]
i think u need a couple more cases

**Comment by erl-ang** [comment]
hi @HongSenDu,

i found it! i think you forgot to enumerate the if cases for 22 - 100 

lmk if this helps 💯

**Comment by jesspli2192** [comment]
thank you, erin liang!

**Comment by HongSenDu** [comment]
thanks guys ☺️
